# Generated by Django 5.1.4 on 2026-04-23 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Временной слот',
                'verbose_name_plural': 'Временные слоты',
                'ordering': ['date', 'start_time'],
                'unique_together': {('date', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('service', models.CharField(blank=True, choices=[('parking', '🅿️ Парковка без страха и суеты'), ('joy', '✨ Возвращаю радость вождения'), ('city', '🏙️ Город как знакомый маршрут'), ('route', '🛣️ Мой любимый маршрут (дом — работа — дом)'), ('antistress', '🧘 Антистресс-вождение'), ('mom', '👨\u200d👩\u200d👧 Мама за рулём'), ('night', '🌙 Свидание с городом (ночные покатушки)'), ('maneuver', '🔄 Маневрирование без паники'), ('other', 'Другое')], max_length=20, verbose_name='Услуга')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='core.timeslot', verbose_name='Слот')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['slot__date', 'slot__start_time'],
            },
        ),
    ]
