# Generated by Django 5.1.4 on 2026-04-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_note',
            field=models.TextField(blank=True, verbose_name='Заметки инструктора'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
    ]
