# Generated by Django 5.1.4 on 2026-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_owner_note_alter_booking_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
