# Generated by Django 5.1.4 on 2026-04-23 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slot_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата занятия (кэш)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_time_str',
            field=models.CharField(blank=True, max_length=20, verbose_name='Время занятия (кэш)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='core.timeslot', verbose_name='Слот'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
